---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed.34.84.105.184.nip.io
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - testbed.34.84.105.184.nip.io
  - argocd.34.84.105.184.nip.io
  - tekton.34.84.105.184.nip.io
  - harbor.34.84.105.184.nip.io
  - notary.34.84.105.184.nip.io
  - dashboard.34.84.105.184.nip.io
  - rook.34.84.105.184.nip.io
  - prometheus.34.84.105.184.nip.io
  - grafana.34.84.105.184.nip.io
  - alertmanager.34.84.105.184.nip.io
  - weave-scope.34.84.105.184.nip.io
  - yugabyte.34.84.105.184.nip.io
  - minio.34.84.105.184.nip.io
  commonName: testbed.34.84.105.184.nip.io
