---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: cart
  namespace: cart
  labels:
    service: cart
    role: proxy
spec:
  routes:
    - services:
        - name: cart
          port: 8080
      permitInsecure: true
