---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  namespace: comment
  labels:
    service: comment
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: comment
      role: app
  template:
    metadata:
      labels:
        service: comment
        role: app
    spec:
      containers:
        - name: comment
          image: registry-harbor-core.infra.svc.cluster.local/library/comment:be966e8f8d1c686e9a7b6908447465a36decd984
          env:
            - name: DB_HOST
              value: comment-db.comment.svc.cluster.local
            - name: DB_PORT
              value: "27017"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: comment-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comment-db
                  key: password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: comment-db-init-script
                  key: dbname
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtkey
                  key: id_ecdsa_521.pub
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: comment
  namespace: comment
  labels:
    service: comment
    role: app
  annotations:
    contour.heptio.com/upstream-protocol.h2c: "8080"
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: comment
    role: app
---
apiVersion: v1
kind: Secret
metadata:
  name: jwtkey
  namespace: comment
  labels:
    service: comment
    role: app
stringData:
  id_ecdsa_521.pub: |
    -----BEGIN PUBLIC KEY-----
    MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBjjADY22rVltjskWUQBxRHOftt1JQ
    use7YfTpH8HVj6XFMQLjlTFLx2zcUyS2N3VnyfIGQpxG+HQ51FjSir5u604B+s+/
    MQJBgk3xndzo+qhO1x+iLSwGNUdMeOTzDfu2oihta2dyRQwd6FQvnqLE7LA8ZWIS
    7CtuWc6IFAUvbxeCEzw=
    -----END PUBLIC KEY-----
