---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-status
  namespace: delivery-status
  labels:
    service: delivery-status
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: delivery-status
      role: app
  template:
    metadata:
      labels:
        service: delivery-status
        role: app
    spec:
      containers:
        - name: delivery-status-app
          image: registry-harbor-core.infra.svc.cluster.local/library/delivery-status:7e3509db4206f0754b817be11f110edd3d966d46
          env:
          - name: DB_HOST
            value: delivery-status-db-mysql-master.delivery-status.svc.cluster.local
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: delivery-status-db
                key: USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: delivery-status-db
                key: PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: delivery-status-db
                key: DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-status
  namespace: delivery-status
  labels:
    service: delivery-status
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: delivery-status
    role: app
---
## nats-sub -s nats://$(cat /var/run/secrets/nats.io/token)@delivery-status-queue.delivery-status.svc.cluster.local:4222 foo.bar
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nats-user-pod
#   namespace: delivery-status
#   labels:
#     nats_cluster: delivery-status-queue
# spec:
#   volumes:
#     - name: "token"
#       projected:
#         sources:
#         - secret:
#             name: "nats-user-delivery-status-queue-bound-token"
#             items:
#               - key: token
#                 path: "token"
#   restartPolicy: Never
#   containers:
#     - name: nats-ops
#       command: ["/bin/sh"]
#       image: "wallyqs/nats-ops:latest"
#       tty: true
#       stdin: true
#       stdinOnce: true
# 
#       # Service Account Token is mounted via projected volume.
#       volumeMounts:
#       - name: "token"
#         mountPath: "/var/run/secrets/nats.io"
#         readOnly: true
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nats-admin-user-pod
#   namespace: delivery-status
#   labels:
#     nats_cluster: delivery-status-queue
# spec:
#   volumes:
#     - name: "token"
#       projected:
#         sources:
#         - secret:
#             name: "nats-admin-user-delivery-status-queue-bound-token"
#             items:
#               - key: token
#                 path: "token"
#   restartPolicy: Never
#   containers:
#     - name: nats-ops
#       command: ["/bin/sh"]
#       image: "wallyqs/nats-ops:latest"
#       tty: true
#       stdin: true
#       stdinOnce: true
# 
#       # Service Account Token is mounted via projected volume.
#       volumeMounts:
#       - name: "token"
#         mountPath: "/var/run/secrets/nats.io"
#         readOnly: true
