apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/__GITHUB_ORG_NAME__/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/infra/nats
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nats-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

