apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-info-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-native-testbed/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/payment-info
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-info
  syncPolicy:
    automated:
      prune: true

