# git clone https://github.com/oracle/mysql-operator.git
# cd oracle-mysql-operator
# helm2 template oracle-mysql-operator > ../oracle-mysql-operator.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: oracle-mysql-operator
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-mysql-operator
  namespace: oracle-mysql-operator
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: oracle-mysql-operator
---
# Source: oracle-mysql-operator/templates/01-resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
  labels:
    release: RELEASE-NAME
    chart: oracle-mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cluster
    singular: mysqlcluster
    plural: mysqlclusters
---
# Source: oracle-mysql-operator/templates/01-resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.oracle.com
  labels:
    release: RELEASE-NAME
    chart: oracle-mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Backup
    singular: mysqlbackup
    plural: mysqlbackups
---
# Source: oracle-mysql-operator/templates/01-resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlrestores.mysql.oracle.com
  labels:
    release: RELEASE-NAME
    chart: oracle-mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Restore
    singular: mysqlrestore
    plural: mysqlrestores
---
# Source: oracle-mysql-operator/templates/01-resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.oracle.com
  labels:
    release: RELEASE-NAME
    chart: oracle-mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: BackupSchedule
    singular: mysqlbackupschedule
    plural: mysqlbackupschedules
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: oracle-mysql-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - create

  - apiGroups: [""]
    resources:
    - services
    verbs:
    - create
    - get
    - list
    - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlbackups"]
    verbs: ["create"]
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: mysql-agent
  namespace: oracle-mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql-agent
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: oracle-mysql-operator
---
# Source: oracle-mysql-operator/templates/02-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: oracle-mysql-operator
  namespace: oracle-mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: oracle-mysql-operator
subjects:
- kind: ServiceAccount
  name: oracle-mysql-operator
  namespace: oracle-mysql-operator
---
# Source: oracle-mysql-operator/templates/03-deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oracle-mysql-operator
  namespace: oracle-mysql-operator
  labels:
    release: RELEASE-NAME
    chart: oracle-mysql-operator-0.2.1
    app: oracle-mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-mysql-operator
  template:
    metadata:
      labels:
        app: oracle-mysql-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: oracle-mysql-operator
      containers:
      - name: oracle-mysql-operator-controller
        imagePullPolicy: Always
        image: iad.ocir.io/oracle/mysql-operator:0.3.0
        ports:
        - containerPort: 10254
        args:
          - --v=4
          - --mysql-agent-image=iad.ocir.io/oracle/mysql-agent
