---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: product
  labels:
    service: product
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: product
      role: app
  template:
    metadata:
      labels:
        service: product
        role: app
    spec:
      containers:
        - name: product-app
          image: registry-harbor-core.infra.svc.cluster.local/library/product:34a81abdc720377e16ac2dbedbf13b74e2b1550e
          env:
            - name: DB_HOST
              value: product-db-mysql-master.product.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: DATABASE
            - name: S3_HOST
              value: minio-hl-svc.infra.svc.cluster.local
            - name: S3_PORT
              value: "9000"
            - name: S3_BUCKET_NAME
              value: product-image
            - name: S3_PUBLIC_HOST
              value: minio.34.84.105.184.nip.io
            - name: S3_PUBLIC_PORT
              value: "443"
            - name: S3_ACCESS_KEY_ID
              value: minio
            - name: S3_SECRET_ACCESS_KEY
              value: miniosecret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: product
  labels:
    service: product
    role: app
  annotations:
    contour.heptio.com/upstream-protocol.h2c: "8080"
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: product
    role: app
